version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bookstore_db
      - SPRING_DATASOURCE_USERNAME=bookstore_user
      - SPRING_DATASOURCE_PASSWORD=0000
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bookstore_db
      POSTGRES_USER: bookstore_user
      POSTGRES_PASSWORD: 0000
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
