name: CI/CD for Bookstore App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '18'

    - name: Build with Maven
      run: ./mvnw clean install

    - name: Build Docker Image
      run: docker build -t bookstore-app .

    - name: Stop and Remove existing container
      run: |
        docker stop bookstore-container || true
        docker rm bookstore-container || true

    - name: Run Docker Container
      run: |
        docker run -d -p 8080:8080 --name bookstore-container bookstore-app
